.PHONY: clean All

All:
	@echo "----------Building project:[ studycpp11 - Debug ]----------"
	@cd "/home/ydu/code/codelite/studycpp11" && "$(MAKE)" -f  "studycpp11.mk"
clean:
	@echo "----------Cleaning project:[ studycpp11 - Debug ]----------"
	@cd "/home/ydu/code/codelite/studycpp11" && "$(MAKE)" -f  "studycpp11.mk" clean
